apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
     app: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: k8s.gcr.io/nginx-slim:0.8
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: /var/www/html
          name: nginx-data
      volumes:
      - name: nginx-data
        persistentVolumeClaim:
          claimName: portworx-demo-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  labels:
    app: nginx
spec:
  type: NodePort
  ports:
  - port: 80
    protocol: TCP
  selector:
    app: nginx