kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: portworx-demo-pvc
  annotations:
    volume.beta.kubernetes.io/storage-class: portworx-demo-sc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi