kind: StorageCluster
apiVersion: core.libopenstorage.org/v1
metadata:
  name: portworx-cluster-5ee70b52-ce62-44a1-8f51-399757f745fc
  namespace: kube-system
  annotations:
    portworx.io/install-source: "https://install.portworx.com/?operator=true&mc=false&b=true&s=%2Fdev%2Fnvme2n1&c=portworx-cluster-5ee70b52-ce62-44a1-8f51-399757f745fc&stork=true&csi=true&mon=true&tel=false&st=k8s&promop=true"
spec:
  image: portworx/oci-monitor:2.11.4
  imagePullPolicy: Always
  kvdb:
    internal: true
  storage:
    devices:
    - /dev/nvme2n1
  secretsProvider: k8s
  stork:
    enabled: true
    args:
      webhook-controller: "true"
  autopilot:
    enabled: true
  csi:
    enabled: true
  monitoring:
    prometheus:
      enabled: true
      exportMetrics: true
